version: "3"

services:
  web:
    container_name: exampleapp
    restart: always
    build: .
    ports: 
      - "5000:3000"
    links:
      - mongo
    volumes:
      - .:/usr/src/app

  mongodb:
    container_name: mydb
    image: mongo
    ports:
      - "27018:27017"
    logging:
      driver: none
    
    